---
abstract: "Corion's Own Web Scraper"
author:
  - 'Max Maischein <corion@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test2::V0: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.44, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: COWS
no_index:
  directory:
    - t
    - inc
requires:
  Carp: '0'
  Exporter: '5'
  JSON: '0'
  List::Util: '0'
  Mojolicious: '0'
  Moo: '2'
  Text::Table: '0'
  URI: '0'
  XML::Feed: '0'
  XML::LibXML: '0'
  perl: '5.020'
resources:
  bugtracker: https://github.com/Corion/COWS/issues
  license: https://dev.perl.org/licenses/
  repository: git://github.com/Corion/COWS.git
version: '0.01'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
x_static_install: 1
